name: analytix
description: A Flutter library for custom analytics manager, capable of sending events to multiple analytics services. Also, it provides a way to gather information about the user's device and the app itself.
version: 1.0.3
repository: https://github.com/unix14/analytix
homepage: https://github.com/unix14/analytix

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  csv: ^6.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0